spring:
  application:
    name: miniconnect
  datasource:
    url: jdbc:postgresql://localhost:5432/miniconnect
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  miniconnect:
    app:
      jwtCookieName: miniconnectapp
      jwtExpirationMs: 3000000
      jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm